
fluidPage(
  # Application title
  titlePanel("USAero"),
  h4("What is USAero?"),
  h6("USAero is a web app that aims to understand the causes and the consequences of airplane accidents based on the data we obtained.
     "),
  
  h3("What do you want to know?"),
  h4("Airplane Accident Trend"),
  img(src="unnamed-chunk-1-2.png"),
  
  # Copy the line below to make a select box 
  selectInput("select1", label = h4("Accident Type & Number"), 
              choices = list("Accident" = length(which(AviationData$Investigation.Type == "Accident")),
                             "Incident" = length(which(AviationData$Investigation.Type == "Incident"))), 
              selected = 1),
  
  hr(),
  fluidRow(column(3, verbatimTextOutput("value1"))),
  
  
  
  
  
  h4("Airplane Accident Injury Severity by Category"),
  img(src="unnamed-chunk-2-2.png"),
  selectInput("select2", label = h4("Accident Type & Number"), 
              choices = list("Non-Fatal" = length(which(AviationData$Injury.Severity == "Non-Fatal")),
                             "Fatal(1)" = length(which(AviationData$Injury.Severity == "Fatal(1)")),
                             "Fatal(2)" = length(which(AviationData$Injury.Severity == "Fatal(2)")),
                             "Fatal(3)" = length(which(AviationData$Injury.Severity == "Fatal(3)")),
                             "Fatal(4)" = length(which(AviationData$Injury.Severity == "Fatal(4)"))
              ), 
              selected = 1),
  
  hr(),
  fluidRow(column(3, verbatimTextOutput("value2"))),
  
  
  
  h4("Airplane Damage by Category"),
  img(src="unnamed-chunk-2-1.png"),
  
  selectInput("select4", label = h4("Place of Accident & The Number of Accidents"), 
              choices = list("Afghanistan" = length(which(AviationData$Country == "Afghanistan")), 
                             "Algeria" = length(which(AviationData$Country == "Algeria")), 
                             "American Samoa" = length(which(AviationData$Country == "American Samoa")), 
                             "Angola" = length(which(AviationData$Country == "Angola")), 
                             "Anguilla" = length(which(AviationData$Country == "Anguilla")), 
                             "Antarctica" = length(which(AviationData$Country == "Antarctica")), 
                             "Antigua And Barbuda" = length(which(AviationData$Country == "Antigua and Barbuda")), 
                             "Argentina" = length(which(AviationData$Country == "Argentina")), 
                             "Aruba" = length(which(AviationData$Country == "Aruba")), 
                             "Australia" = length(which(AviationData$Country == "Australia")), 
                             "Austria" = length(which(AviationData$Country == "Austria")), 
                             "Bahamas" = length(which(AviationData$Country == "Bahamas")), 
                             "Bahrain" = length(which(AviationData$Country == "Bahrain")), 
                             "Bangladesh" = length(which(AviationData$Country == "Bangladesh")), 
                             "Barbados" = length(which(AviationData$Country == "Barbados")), 
                             "Belarus" = length(which(AviationData$Country == "Belarus")), 
                             "Belgium" = length(which(AviationData$Country == "Belgium")), 
                             "Belize" = length(which(AviationData$Country == "Belize")), 
                             "Benin" = length(which(AviationData$Country == "Benin")), 
                             "Bermuda" = length(which(AviationData$Country == "Bermuda")),
                             "Bolivia" = length(which(AviationData$Country == "Bolivia")), 
                             "Bosnia And Herzegovina" = length(which(AviationData$Country == "Bosnia and Herzegovina")), 
                             "Botswana" = length(which(AviationData$Country == "Bermuda")), 
                             "Brazil" = length(which(AviationData$Country == "Brazil")), 
                             "British Virgin Islands" = length(which(AviationData$Country == "British Virgin Islands")), 
                             "Bulgaria" = length(which(AviationData$Country == "Bulgaria")), 
                             "Burma" = length(which(AviationData$Country == "Burma")), 
                             "Cambodia" = length(which(AviationData$Country == "Cambodia")), 
                             "Cameroon" = length(which(AviationData$Country == "Cameroon")), 
                             "Canada" = length(which(AviationData$Country == "Canada")), 
                             "Cayman Islands" = length(which(AviationData$Country == "Cayman Islands")), 
                             "Central African Republic" = length(which(AviationData$Country == "Central African Republic")),
                             "Chile" = length(which(AviationData$Country == "Chile")), 
                             "China" = length(which(AviationData$Country == "China")), 
                             "Colombia" = length(which(AviationData$Country == "Colombia")), 
                             "Comoros" = length(which(AviationData$Country == "Comoros")), 
                             "Congo" = length(which(AviationData$Country == "Congo")), 
                             "Costa Rica" = length(which(AviationData$Country == "Costa Rica")), 
                             "Cote D'ivoire" = length(which(AviationData$Country == "Cote D'ivoire")), 
                             "Croatia" = length(which(AviationData$Country == "Croatia")), 
                             "Cuba" = length(which(AviationData$Country == "Cuba")), 
                             "Cyprus" = length(which(AviationData$Country == "Cyprus")), 
                             "Czech Republic" = length(which(AviationData$Country == "Czech Republic")), 
                             "Denmark" = length(which(AviationData$Country == "Denmark")), 
                             "Dominica" = length(which(AviationData$Country == "Dominica")), 
                             "Dominican Republic" = length(which(AviationData$Country == "Dominican Republic")), 
                             "Ecuador" = length(which(AviationData$Country == "Ecuador")), 
                             "Egypt" = length(which(AviationData$Country == "Egypt")), 
                             "El Salvador" = length(which(AviationData$Country == "El Salvador")), 
                             "Eritrea" =length(which(AviationData$Country == "Eritrea")), 
                             "Estonia" = length(which(AviationData$Country == "Estonia")), 
                             "Ethiopia" = length(which(AviationData$Country == "Ethiopia")), 
                             "Federated States Of Micronesia" = length(which(AviationData$Country == "Federated States of Micronesia")),  
                             "Fiji" = length(which(AviationData$Country == "Fiji")), 
                             "Finland" = length(which(AviationData$Country == "Finland")), 
                             "France" = length(which(AviationData$Country == "France")), 
                             "French Guiana" = length(which(AviationData$Country == "French Guiana")), 
                             "French Polynesia" = length(which(AviationData$Country == "French Polynesia")), 
                             "Gabon" = length(which(AviationData$Country == "Gabon")), 
                             "Gambia" = length(which(AviationData$Country == "Gambia")), 
                             "Germany" = length(which(AviationData$Country == "Germany")), 
                             "Ghana" = length(which(AviationData$Country == "Ghana")),  
                             "Gibraltar" = length(which(AviationData$Country == "Gibraltar")), 
                             "Greece" = length(which(AviationData$Country == "Greece")), 
                             "Greenland" = length(which(AviationData$Country == "Greenland")), 
                             "Guadeloupe" = length(which(AviationData$Country == "Guadelope")), 
                             "Guatemala" = length(which(AviationData$Country == "Guatemala")), 
                             "Guinea" = length(which(AviationData$Country == "Guinea")), 
                             "Guyana" = length(which(AviationData$Country == "Guyana")), 
                             "Haiti" = length(which(AviationData$Country == "Haiti")), 
                             "Honduras" = length(which(AviationData$Country == "Honduras")), 
                             "Hong Kong" = length(which(AviationData$Country == "Hong Kong")), 
                             "Hungary" = length(which(AviationData$Country == "Hungary")), 
                             "Iceland" = length(which(AviationData$Country == "Iceland")), 
                             "India"= length(which(AviationData$Country == "India")), 
                             "Indonesia"=length(which(AviationData$Country == "Indonesia")), 
                             "Iran"=length(which(AviationData$Country == "Iran")), 
                             "Iraq"=length(which(AviationData$Country == "Iraq")), 
                             "Ireland"=length(which(AviationData$Country == "Ireland")), 
                             "Isle of Man"=length(which(AviationData$Country == "Isle of Man")), 
                             "Israel"=length(which(AviationData$Country == "Israel")), 
                             "Italy"=length(which(AviationData$Country == "Italy")), 
                             "Ivory Coast"=length(which(AviationData$Country == "Ivory Coast")), 
                             "Jamaica"=length(which(AviationData$Country == "Jamaica")), 
                             "Japan"=length(which(AviationData$Country == "Japan")), 
                             "Jordan"=length(which(AviationData$Country == "Jordan")), 
                             "Kazakhstan"=length(which(AviationData$Country == "Kazakhstan")), 
                             "Kenya"=length(which(AviationData$Country == "Kenya")), 
                             "Kiribati"=length(which(AviationData$Country == "Kiribati")), 
                             "Korea, Republic Of"=length(which(AviationData$Country == "Korea, Republic Of")), 
                             "Kyrgyzstan"=length(which(AviationData$Country == "Kyrgyzstan")), 
                             "Laos"=length(which(AviationData$Country == "Laos")), 
                             "Latvia"=length(which(AviationData$Country == "Latvia")), 
                             "Lebanon"=length(which(AviationData$Country == "Lebanon")), 
                             "Liberia"=length(which(AviationData$Country == "Liberia")), 
                             "Libya"=length(which(AviationData$Country == "Libya")), 
                             "Lithuania"=length(which(AviationData$Country == "Lithuania")), 
                             "Luxembourg"=length(which(AviationData$Country == "Luxembourg")), 
                             "Macedonia"=length(which(AviationData$Country == "Macedonia")), 
                             "Madagascar"=length(which(AviationData$Country == "Madagascar")), 
                             "Malawi"=length(which(AviationData$Country == "Malawi")), 
                             "Malaysia" = length(which(AviationData$Country == "Malaysia")), 
                             "Maldives" = length(which(AviationData$Country == "Maldives")), 
                             "Mali"=length(which(AviationData$Country == "Mali")), 
                             "Malta" =length(which(AviationData$Country == "Malta")), 
                             "Marshall Islands"=length(which(AviationData$Country == "Marshall Islands")), 
                             "Martinique" = length(which(AviationData$Country == "Martinique")), 
                             "Mauritania" = length(which(AviationData$Country == "Mauritania")), 
                             "Mauritius" = length(which(AviationData$Country == "Mauritius")), 
                             "Mexico" = length(which(AviationData$Country == "Mexico")), 
                             "Montserrat" = length(which(AviationData$Country == "Montserrat")), 
                             "Morocco" = length(which(AviationData$Country == "Morocco")), 
                             "Mozambique" = length(which(AviationData$Country == "Mozambique")), 
                             "Namibia"=length(which(AviationData$Country == "Namibia")), 
                             "Nauru" =length(which(AviationData$Country == "Nauru")), 
                             "Nepal" =length(which(AviationData$Country == "Nepal")), 
                             "Netherlands" = length(which(AviationData$Country == "Netherlands")), 
                             "Netherlands Antilles"=length(which(AviationData$Country == "Netherlands Antilles")),
                             "New Caledonia" = length(which(AviationData$Country == "New Caledonia")), 
                             "New Zealand" = length(which(AviationData$Country == "New Zealand")), 
                             "Nicaragua" = length(which(AviationData$Country == "Nicaragua")), 
                             "Niger" = length(which(AviationData$Country == "Niger")), 
                             "Nigeria" = length(which(AviationData$Country == "Nigeria")), 
                             "Northern Mariana Islands" = length(which(AviationData$Country == "Northern Mariana Islands")), 
                             "Norway" = length(which(AviationData$Country == "Norway")), 
                             "Oman" = length(which(AviationData$Country == "Oman")), 
                             "Pakistan" = length(which(AviationData$Country == "Pakistan")), 
                             "Palau" = length(which(AviationData$Country == "Palau")), 
                             "Panama" = length(which(AviationData$Country == "Panama")), 
                             "Papua New Guinea" = length(which(AviationData$Country == "Papua New Guinea")), 
                             "Paraguay" = length(which(AviationData$Country == "Paraguay")), 
                             "Peru" = length(which(AviationData$Country == "Peru")), 
                             "Philippines" = length(which(AviationData$Country == "Phillipines")), 
                             "Poland" = length(which(AviationData$Country == "Poland")), 
                             "Portugal" = length(which(AviationData$Country == "Portugal")), 
                             "Qatar" = length(which(AviationData$Country == "Qatar")), 
                             "Reunion"=length(which(AviationData$Country == "Reunion")), 
                             "Romania" = length(which(AviationData$Country == "Romania")), 
                             "Russia" = length(which(AviationData$Country == "Russia")), 
                             "Rwanda" = length(which(AviationData$Country == "Rwanda")), 
                             "Saudi Arabia" = length(which(AviationData$Country == "Saudi Arabia")), 
                             "Senegal" = length(which(AviationData$Country == "Senegal")), 
                             "Serbia" = length(which(AviationData$Country == "Serbia")), 
                             "Sierra Leone" = length(which(AviationData$Country == "Sierra Leone")), 
                             "Singapore" = length(which(AviationData$Country == "Singapore")), 
                             "Slovakia" = length(which(AviationData$Country == "Slovakia")), 
                             "Slovenia" = length(which(AviationData$Country == "Slovenia")), 
                             "Solomon Islands" = length(which(AviationData$Country == "Solomon Islands")), 
                             "South Africa" = length(which(AviationData$Country == "South Africa")), 
                             "Spain" = length(which(AviationData$Country == "Spain")), 
                             "St Kitts And Nevis" = length(which(AviationData$Country == "St Kitts And Nevis")), 
                             "St Lucia" = length(which(AviationData$Country == "St Lucia")), 
                             "St Vincent And The Grenadines" = length(which(AviationData$Country == "St Vincent And The Grenadines")), 
                             "Sudan" = length(which(AviationData$Country == "Sudan")), 
                             "Suriname" = length(which(AviationData$Country == "Suriname")), 
                             "Sweden" = length(which(AviationData$Country == "Sweden")), 
                             "Switzerland" = length(which(AviationData$Country == "Switzerland")), 
                             "Taiwan" = length(which(AviationData$Country == "Taiwan")), 
                             "Tanzania" = length(which(AviationData$Country == "Tanzania")), 
                             "Thailand" = length(which(AviationData$Country == "Thailand")), 
                             "Trinidad And Tobago" = length(which(AviationData$Country == "Trinidad and Tobago")), 
                             "Tunisia" = length(which(AviationData$Country == "Tunisia")), 
                             "Turkey" = length(which(AviationData$Country == "Turkey")), 
                             "Turks And Caicos Islands" = length(which(AviationData$Country == "Turks And Caicos Islands")), 
                             "Uganda" = length(which(AviationData$Country == "Uganda")), 
                             "Ukraine" = length(which(AviationData$Country == "Ukraine")), 
                             "United Arab Emirates" = length(which(AviationData$Country == "United Arab Emirates")), 
                             "United Kingdom" = length(which(AviationData$Country == "United Kingdom")), 
                             "United States" = length(which(AviationData$Country == "United States")), 
                             "Uruguay" = length(which(AviationData$Country == "Uruguay")), 
                             "Vanuatu" = length(which(AviationData$Country == "Vanuatu")), 
                             "Venezuela" = length(which(AviationData$Country == "Venezuela")), 
                             "Vietnam" = length(which(AviationData$Country == "Vietnam")), 
                             "West Indies" = length(which(AviationData$Country == "West Indies")), 
                             "Yemen" = length(which(AviationData$Country == "Yemen")), 
                             "Zambia" = length(which(AviationData$Country == "Zambia")), 
                             "Zimbabwe" = length(which(AviationData$Country == "Zimbabwe"))), 
              selected = 1),
  
  hr(),
  fluidRow(list(verbatimTextOutput("value4"))),
  
  selectInput("select5", label = h4("Airplane Make"), 
              choices = list("AERO COMMANDER"= 415, "AEROSPATIALE" = 377,"AIR TRACTOR"= 809, "BOEING" = 140,"Cesna" = 1145, "ENSTROM"= 286, "MOONEY" =1297, "PIPER" = 614, "SCHLEICHER"=146, "WEATHERLY"=101), 
              selected = 1),
  
  hr(),
  fluidRow(list(verbatimTextOutput("value5")))
  )